services:
  - type: web
    name: project-vantage-backend
    env: python
    buildCommand: "apt-get update && apt-get install -y iputils-ping && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
